name: Docs PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs-preview.yml"

concurrency:
  group: docs-preview-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        if: github.event.action != 'closed'
        uses: actions/cache@v4
        with:
          path: node_modules
          key: preview-npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            preview-npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Build docs
        if: github.event.action != 'closed'
        run: |
          npm run docs:build
        env:
          PR_NUMBER: ${{ github.event.number }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./apps/docs/build/
